require("sumanthyedoti.options")
require("sumanthyedoti.keymaps")
require("sumanthyedoti.autocommands")
require("sumanthyedoti.lazy-plugin-manager")
require("sumanthyedoti.theme")
require("sumanthyedoti.custom")
