# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

# Replace the '❯' symbol in the prompt with '➜'
[character]
success_symbol = "[\uf054](white)" # 
vicmd_symbol = "[\ue62b](white)" # 
error_symbol = "[\uf467](red)" # 

[directory]
style = "blue bold"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = false

[username]
disabled = false

[hostname]
disabled = false

[aws]
disabled = false

[docker_context]
disabled = false

[git_branch]
disabled = false

[git_commit]
disabled = false

[git_state]
disabled = false

[git_metrics]
disabled = false

[git_status]
disabled = false
