# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true
# move the rest of the prompt to the right
# right_format = """$all"""

palette = "catppuccin_mocha"

# A minimal left prompt
# format = """
# [$directory $git_branch $git_metrics](white bold bg:#708090)\
# [](#708090)
# $character
# """
# format = """
# $directory $git_branch $git_metrics
# $character
# """

# Replace the '❯' symbol in the prompt with '➜'
[character]
success_symbol = "[\uf054](white)" # 
vicmd_symbol = "[\ue62b](white)" # 
error_symbol = "[\uf467\uf460](red)" # 

[directory]
# style = "white bg:#708090"
# format = "[ $path ]($style)"
truncation_length = 2
truncation_symbol = ".../"
[directory.substitutions]
"Downloads" = "📥"
"Pictures" = "📷"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = false

[username]
disabled = false

[hostname]
disabled = false

[aws]
format = 'on [$symbol($profile )(\($region\) )]($style)'
style = 'bold blue'
symbol = " "

[docker_context]
disabled = false

[git_branch]
# style = "#00FFFF bold bg:#708090"
disabled = false

[git_commit]
disabled = false

[git_state]
disabled = false

[git_metrics]
disabled = false

[git_status]
disabled = false


[golang]
format = '[ $version](bold cyan) '
detect_files = ['go.mod']

[kubernetes]
symbol = '☸'
disabled = false
detect_files = ['k8s', 'Dockerfile']
detect_extensions = ['yaml']
format = '[$symbol$context( \($namespace\))]($style) '
[kubernetes.context_aliases]
'arn:aws:eks:us-west-2:123:cluster/gal-kub-demo-cluster' = 'gal'

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
